'use strict'; // code generated by pbf v3.2.1

var RouteType = exports.RouteType = {
    "UNKNOWN": {
        "value": 1,
        "options": {}
    },
    "BENZOATE": {
        "value": 2,
        "options": {}
    },
    "VALERATE": {
        "value": 3,
        "options": {}
    },
    "CYPIONATE": {
        "value": 4,
        "options": {}
    },
    "ENANTHATE": {
        "value": 5,
        "options": {}
    },
    "UNDECYLATE": {
        "value": 6,
        "options": {}
    },
    "UNDECYLATE_CASUBQ": {
        "value": 7,
        "options": {}
    },
    "PATCH_TW": {
        "value": 8,
        "options": {}
    },
    "PATCH_OW": {
        "value": 9,
        "options": {}
    }
};

// EstrannaiseState ========================================

var EstrannaiseState = exports.EstrannaiseState = {};

EstrannaiseState.read = function (pbf, end) {
    return pbf.readFields(EstrannaiseState._readField, {multi_doses: [], steady_state: []}, end);
};
EstrannaiseState._readField = function (tag, obj, pbf) {
    if (tag === 1) obj.multi_doses.push(Doses.read(pbf, pbf.readVarint() + pbf.pos));
    else if (tag === 2) obj.steady_state.push(Doses.read(pbf, pbf.readVarint() + pbf.pos));
};
EstrannaiseState.write = function (obj, pbf) {
    if (obj.multi_doses) for (var i = 0; i < obj.multi_doses.length; i++) pbf.writeMessage(1, Doses.write, obj.multi_doses[i]);
    if (obj.steady_state) for (i = 0; i < obj.steady_state.length; i++) pbf.writeMessage(2, Doses.write, obj.steady_state[i]);
};

// Doses ========================================

var Doses = exports.Doses = {};

Doses.read = function (pbf, end) {
    return pbf.readFields(Doses._readField, {type: 0, values: []}, end);
};
Doses._readField = function (tag, obj, pbf) {
    if (tag === 1) obj.type = pbf.readVarint();
    else if (tag === 2) obj.values.push(Doses.Value.read(pbf, pbf.readVarint() + pbf.pos));
};
Doses.write = function (obj, pbf) {
    if (obj.type) pbf.writeVarintField(1, obj.type);
    if (obj.values) for (var i = 0; i < obj.values.length; i++) pbf.writeMessage(2, Doses.Value.write, obj.values[i]);
};

// Doses.Value ========================================

Doses.Value = {};

Doses.Value.read = function (pbf, end) {
    return pbf.readFields(Doses.Value._readField, {dose: 0, time: 0, cvisibility: false, uvisibility: false}, end);
};
Doses.Value._readField = function (tag, obj, pbf) {
    if (tag === 1) obj.dose = pbf.readFloat();
    else if (tag === 2) obj.time = pbf.readFloat();
    else if (tag === 3) obj.cvisibility = pbf.readBoolean();
    else if (tag === 4) obj.uvisibility = pbf.readBoolean();
};
Doses.Value.write = function (obj, pbf) {
    if (obj.dose) pbf.writeFloatField(1, obj.dose);
    if (obj.time) pbf.writeFloatField(2, obj.time);
    if (obj.cvisibility) pbf.writeBooleanField(3, obj.cvisibility);
    if (obj.uvisibility) pbf.writeBooleanField(4, obj.uvisibility);
};
